export const PERSONAL_LOGN_SUCCESS = "PERSONAL_LOGN_SUCCESS";
export const PERSONAL_LOGN_INFO = "PERSONAL_LOGN_INFO";

export const CART_ORDERALL = "CART_ORDERALL";
export const CART_SELECT_ALL = "CART_SELECT_ALL";
export const CART_UPDATE_SELECT = "CART_UPDATE_SELECT";
export const CART_EDIT_ALL = "CART_EDIT_ALL";
export const CART_UPDATE_EDIT_ALL = "CART_UPDATE_EDIT_ALL";
export const CART_UPDATE_EDIT = "CART_UPDATE_EDIT";
export const CART_UPDATE_COUNT = "CART_UPDATE_COUNT";
export const CART_REMOVE = "CART_REMOVE";

export const PRO_CG = "PRO_CG";